// Code generated by tools/codegen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/criblio/terraform-provider-criblio/internal/restclient"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ = jsontypes.NormalizedType{}
var _ = types.String{}

var _ datasource.DataSource = &MonitorDataSource{}
var _ datasource.DataSourceWithConfigure = &MonitorDataSource{}

type MonitorDataSource struct {
	client *restclient.Client
	api    MonitorAPI
}

func NewMonitorDataSource() datasource.DataSource {
	return &MonitorDataSource{}
}

func (d *MonitorDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_monitor"
}

func (d *MonitorDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Monitor Data Source",
		Attributes: map[string]schema.Attribute{
			"dataset_id": schema.StringAttribute{
				Computed:    true,
				Description: `Default dataset used for query execution and alert history storage. Per-query overrides are set via the query's datasetId.`,
			},
			"description": schema.StringAttribute{
				Computed:    true,
				Description: `Optional human-readable description of the monitor.`,
			},
			"detection_config": schema.StringAttribute{
				Computed:    true,
				Description: `Type-specific detection configuration for change, anomaly, outlier, and forecast monitors. Use jsonencode({ ... }).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"enabled": schema.BoolAttribute{
				Computed:    true,
				Description: `Whether the monitor is active and evaluated.`,
			},
			"expr": schema.ListNestedAttribute{
				Computed:    true,
				Description: `Query expressions evaluated to produce the monitor's series.`,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"dataset_id": schema.StringAttribute{
							Computed: true,
						},
						"label": schema.StringAttribute{
							Computed: true,
						},
						"left": schema.StringAttribute{
							Computed: true,
						},
						"operation": schema.StringAttribute{
							Computed: true,
						},
						"query_labels": schema.ListAttribute{
							Computed:    true,
							ElementType: types.StringType,
						},
						"right": schema.StringAttribute{
							Computed: true,
						},
						"scalar": schema.Float64Attribute{
							Computed: true,
						},
						"text": schema.StringAttribute{
							Computed: true,
						},
					},
				},
			},
			"firing_condition": schema.SingleNestedAttribute{
				Computed:    true,
				Description: `Condition that determines when the monitor fires. Profile-linked inheritance is not supported by this provider yet.`,
				Attributes: map[string]schema.Attribute{
					"clear_delay": schema.Float64Attribute{
						Computed: true,
					},
					"fire_delay": schema.Float64Attribute{
						Computed: true,
					},
				},
			},
			"firing_rule": schema.SingleNestedAttribute{
				Computed:    true,
				Description: `Rule defining firing thresholds and overrides. Profile-linked inheritance is not supported by this provider yet.`,
				Attributes: map[string]schema.Attribute{
					"label": schema.StringAttribute{
						Computed: true,
					},
					"overrides": schema.ListNestedAttribute{
						Computed: true,
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"enabled": schema.BoolAttribute{
									Computed: true,
								},
								"excluded_tags": schema.ListAttribute{
									Computed:    true,
									ElementType: types.StringType,
								},
								"included_tags": schema.ListAttribute{
									Computed:    true,
									ElementType: types.StringType,
								},
								"name": schema.StringAttribute{
									Computed: true,
								},
								"show_on_chart": schema.BoolAttribute{
									Computed: true,
								},
								"threshold": schema.ListNestedAttribute{
									Computed: true,
									NestedObject: schema.NestedAttributeObject{
										Attributes: map[string]schema.Attribute{
											"excluded_tags": schema.ListAttribute{
												Computed:    true,
												ElementType: types.StringType,
											},
											"included_tags": schema.ListAttribute{
												Computed:    true,
												ElementType: types.StringType,
											},
											"limit": schema.Float64Attribute{
												Computed: true,
											},
											"operator": schema.StringAttribute{
												Computed: true,
											},
											"severity": schema.StringAttribute{
												Computed: true,
											},
											"std_deviations": schema.Float64Attribute{
												Computed: true,
											},
											"times_triggered": schema.Float64Attribute{
												Computed: true,
											},
										},
									},
								},
							},
						},
					},
					"show_on_chart": schema.BoolAttribute{
						Computed: true,
					},
					"threshold": schema.ListNestedAttribute{
						Computed: true,
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"excluded_tags": schema.ListAttribute{
									Computed:    true,
									ElementType: types.StringType,
								},
								"included_tags": schema.ListAttribute{
									Computed:    true,
									ElementType: types.StringType,
								},
								"limit": schema.Float64Attribute{
									Computed: true,
								},
								"operator": schema.StringAttribute{
									Computed: true,
								},
								"severity": schema.StringAttribute{
									Computed: true,
								},
								"std_deviations": schema.Float64Attribute{
									Computed: true,
								},
								"times_triggered": schema.Float64Attribute{
									Computed: true,
								},
							},
						},
					},
				},
			},
			"id": schema.StringAttribute{
				Required:    true,
				Description: `Unique identifier for the monitor.`,
			},
			"managed_by": schema.StringAttribute{
				Computed:    true,
				Description: `Stamped 'terraform' by the backend when provisioned via the Terraform provider (cribl/cribl#43133).`,
			},
			"metadata": schema.MapAttribute{
				Computed:    true,
				Description: `Arbitrary key-value metadata. Profile-linked inheritance is not supported by this provider yet.`,
				ElementType: types.StringType,
			},
			"name": schema.StringAttribute{
				Computed:    true,
				Description: `Human-readable name for the monitor.`,
			},
			"notification": schema.StringAttribute{
				Computed:    true,
				Description: `Notification configuration for the monitor. Use jsonencode({ enabled = false, type = "policy", config = [] }).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"priority": schema.SingleNestedAttribute{
				Computed:    true,
				Description: `Monitor priority. Profile-linked inheritance is not supported by this provider yet -- set value directly, e.g. { value = "P1" }.`,
				Attributes: map[string]schema.Attribute{
					"value": schema.StringAttribute{
						Computed: true,
					},
				},
			},
			"query": schema.MapNestedAttribute{
				Computed:    true,
				Description: `Monitor queries keyed by query label. Each query is inheritable from a linked profile.`,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"builder": schema.SingleNestedAttribute{
							Computed: true,
							Attributes: map[string]schema.Attribute{
								"aggregation": schema.StringAttribute{
									Computed: true,
								},
								"evaluation_window": schema.SingleNestedAttribute{
									Computed: true,
									Attributes: map[string]schema.Attribute{
										"unit": schema.StringAttribute{
											Computed:    true,
											Description: `Time unit for the evaluation window magnitude (for example , , , ).`,
										},
										"value": schema.Float64Attribute{
											Computed:    true,
											Description: `Numeric magnitude of the evaluation window, paired with (for example in "5m").`,
										},
									},
								},
								"group_by": schema.ListAttribute{
									Computed:    true,
									ElementType: types.StringType,
								},
								"label_filters": schema.ListNestedAttribute{
									Computed: true,
									NestedObject: schema.NestedAttributeObject{
										Attributes: map[string]schema.Attribute{
											"key": schema.StringAttribute{
												Computed: true,
											},
											"op": schema.StringAttribute{
												Computed: true,
											},
											"value": schema.StringAttribute{
												Computed: true,
											},
										},
									},
								},
								"metric": schema.StringAttribute{
									Computed: true,
								},
								"units": schema.StringAttribute{
									Computed: true,
								},
							},
						},
						"dataset_id": schema.StringAttribute{
							Computed: true,
						},
						"display_name": schema.StringAttribute{
							Computed: true,
						},
						"logs_builder": schema.SingleNestedAttribute{
							Computed: true,
							Attributes: map[string]schema.Attribute{
								"dataset": schema.StringAttribute{
									Computed: true,
								},
								"evaluation_window": schema.SingleNestedAttribute{
									Computed: true,
									Attributes: map[string]schema.Attribute{
										"unit": schema.StringAttribute{
											Computed:    true,
											Description: `Time unit for the evaluation window magnitude (for example , , , ).`,
										},
										"value": schema.Float64Attribute{
											Computed:    true,
											Description: `Numeric magnitude of the evaluation window, paired with (for example in "5m").`,
										},
									},
								},
								"field": schema.StringAttribute{
									Computed: true,
								},
								"group_by": schema.ListAttribute{
									Computed:    true,
									ElementType: types.StringType,
								},
								"operator": schema.StringAttribute{
									Computed: true,
								},
								"parent_search": schema.StringAttribute{
									Computed: true,
								},
								"saved_search_id": schema.StringAttribute{
									Computed: true,
								},
							},
						},
						"mode": schema.StringAttribute{
							Computed: true,
						},
						"params": schema.MapAttribute{
							Computed:    true,
							ElementType: types.StringType,
						},
						"promql": schema.StringAttribute{
							Computed: true,
						},
					},
				},
			},
			"search_mode": schema.StringAttribute{
				Computed:    true,
				Description: `Logs monitors only. Distinguishes authoring a fresh search ('new') from selecting a saved one ('saved'). Defaults to 'new' when omitted; ignored for non-logs monitor types.`,
			},
			"team": schema.SingleNestedAttribute{
				Computed:    true,
				Description: `Owning team. Profile-linked inheritance is not supported by this provider yet -- set value directly, e.g. { value = "platform" }.`,
				Attributes: map[string]schema.Attribute{
					"value": schema.StringAttribute{
						Computed: true,
					},
				},
			},
			"template_params": schema.StringAttribute{
				Computed:    true,
				Description: `Template parameter bindings keyed by query label. Use jsonencode({ A = { ... } }).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"type": schema.StringAttribute{
				Computed:    true,
				Description: `Monitor type, which determines the detection strategy (for example threshold, change, anomaly, outlier, forecast, or logs).`,
			},
			"unit": schema.StringAttribute{
				Computed:    true,
				Description: `Optional unit label applied to the monitor's values.`,
			},
		},
	}
}

func (d *MonitorDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	clients, ok := req.ProviderData.(*ProviderClients)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *ProviderClients, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	d.client = clients.RC
	d.api = newMonitorAPI(d.client)
}

func (d *MonitorDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var model MonitorModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &model)...)
	if resp.Diagnostics.HasError() {
		return
	}
	apiModel, err := d.api.Read(ctx, model)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		return
	}
	applyMonitorAPIToState(apiModel, &model, false, false)
	resp.Diagnostics.Append(resp.State.Set(ctx, &model)...)
}

func MonitorDataSourceDebug(value any) string {
	return fmt.Sprintf("%v", value)
}
