// Code generated by tools/codegen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/criblio/terraform-provider-criblio/internal/restclient"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ = jsontypes.NormalizedType{}
var _ = types.String{}

var _ datasource.DataSource = &MonitorDataSource{}
var _ datasource.DataSourceWithConfigure = &MonitorDataSource{}

type MonitorDataSource struct {
	client *restclient.Client
	api    MonitorAPI
}

func NewMonitorDataSource() datasource.DataSource {
	return &MonitorDataSource{}
}

func (d *MonitorDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_monitor"
}

func (d *MonitorDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Monitor Data Source",
		Attributes: map[string]schema.Attribute{
			"dataset_id": schema.StringAttribute{
				Computed:    true,
				Description: `Default dataset used for query execution and alert history storage. Per-query overrides are set via the query's datasetId.`,
			},
			"description": schema.StringAttribute{
				Computed:    true,
				Description: `Optional human-readable description of the monitor.`,
			},
			"detection_config": schema.StringAttribute{
				Computed:    true,
				Description: `Type-specific detection configuration for change, anomaly, outlier, and forecast monitors. Use jsonencode({ ... }).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"enabled": schema.BoolAttribute{
				Computed:    true,
				Description: `Whether the monitor is active and evaluated.`,
			},
			"expr": schema.StringAttribute{
				Computed:    true,
				Description: `Query expressions evaluated to produce the monitor's series. Use jsonencode([...]).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"firing_condition": schema.StringAttribute{
				Computed:    true,
				Description: `Condition that determines when the monitor fires. Use jsonencode({ fire_delay = N, clear_delay = M }).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"firing_rule": schema.StringAttribute{
				Computed:    true,
				Description: `Rule defining firing thresholds and overrides. Use jsonencode({ label = "A", threshold = [...] }).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"id": schema.StringAttribute{
				Required:    true,
				Description: `Unique identifier for the monitor.`,
			},
			"managed_by": schema.StringAttribute{
				Computed:    true,
				Description: `Stamped 'terraform' by the backend when provisioned via the Terraform provider (cribl/cribl#43133).`,
			},
			"metadata": schema.StringAttribute{
				Computed:    true,
				Description: `Arbitrary key-value metadata. Use jsonencode({}).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"name": schema.StringAttribute{
				Computed:    true,
				Description: `Human-readable name for the monitor.`,
			},
			"notification": schema.StringAttribute{
				Computed:    true,
				Description: `Notification configuration for the monitor. Use jsonencode({ enabled = false, type = "policy", config = [] }).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"priority": schema.StringAttribute{
				Computed:    true,
				Description: `Monitor priority, inheritable from a linked profile. Use jsonencode({ value = "P1" }).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"query": schema.StringAttribute{
				Computed:    true,
				Description: `Monitor queries keyed by query label. Use jsonencode({ A = { mode = "promql", promql = "..." } }).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"search_mode": schema.StringAttribute{
				Computed:    true,
				Description: `Logs monitors only. Distinguishes authoring a fresh search ('new') from selecting a saved one ('saved'). Defaults to 'new' when omitted; ignored for non-logs monitor types.`,
			},
			"team": schema.StringAttribute{
				Computed:    true,
				Description: `Owning team, inheritable from a linked profile. Use jsonencode({ value = "<team-name>" }).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"template_params": schema.StringAttribute{
				Computed:    true,
				Description: `Template parameter bindings keyed by query label. Use jsonencode({ A = { ... } }).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"type": schema.StringAttribute{
				Computed:    true,
				Description: `Monitor type, which determines the detection strategy (for example threshold, change, anomaly, outlier, forecast, or logs).`,
			},
			"unit": schema.StringAttribute{
				Computed:    true,
				Description: `Optional unit label applied to the monitor's values.`,
			},
		},
	}
}

func (d *MonitorDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	clients, ok := req.ProviderData.(*ProviderClients)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *ProviderClients, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	d.client = clients.RC
	d.api = newMonitorAPI(d.client)
}

func (d *MonitorDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var model MonitorModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &model)...)
	if resp.Diagnostics.HasError() {
		return
	}
	apiModel, err := d.api.Read(ctx, model)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		return
	}
	applyMonitorAPIToState(apiModel, &model, false, false)
	resp.Diagnostics.Append(resp.State.Set(ctx, &model)...)
}

func MonitorDataSourceDebug(value any) string {
	return fmt.Sprintf("%v", value)
}
