// Code generated by tools/codegen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/criblio/terraform-provider-criblio/internal/restclient"
	custom_stringplanmodifier "github.com/criblio/terraform-provider-criblio/internal/tfplanmodifiers/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

var _ = jsontypes.NormalizedType{}
var _ = types.String{}

var _ resource.Resource = &MonitorResource{}
var _ resource.ResourceWithConfigure = &MonitorResource{}
var _ resource.ResourceWithImportState = &MonitorResource{}

type MonitorResource struct {
	client *restclient.Client
	api    MonitorAPI
}

func NewMonitorResource() resource.Resource {
	return &MonitorResource{}
}

func (r *MonitorResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_monitor"
}

func (r *MonitorResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Monitor Resource",
		Attributes: map[string]schema.Attribute{
			"dataset_id": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: `Default dataset used for query execution and alert history storage. Per-query overrides are set via the query's datasetId.`,
			},
			"description": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    false,
				Description: `Optional human-readable description of the monitor.`,
			},
			"detection_config": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: `Type-specific detection configuration for change, anomaly, outlier, and forecast monitors. Use jsonencode({ ... }).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"enabled": schema.BoolAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: `Whether the monitor is active and evaluated.`,
			},
			"expr": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: `Query expressions evaluated to produce the monitor's series. Use jsonencode([...]).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"firing_condition": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: `Condition that determines when the monitor fires. Use jsonencode({ fire_delay = N, clear_delay = M }).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"firing_rule": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: `Rule defining firing thresholds and overrides. Use jsonencode({ label = "A", threshold = [...] }).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"id": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: `Unique identifier for the monitor.`,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
					custom_stringplanmodifier.SuppressDiff(custom_stringplanmodifier.ExplicitSuppress),
				},
			},
			"managed_by": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: `Stamped 'terraform' by the backend when provisioned via the Terraform provider (cribl/cribl#43133).`,
			},
			"metadata": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: `Arbitrary key-value metadata. Use jsonencode({}).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"name": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: `Human-readable name for the monitor.`,
			},
			"notification": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: `Notification configuration for the monitor. Use jsonencode({ enabled = false, type = "policy", config = [] }).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"priority": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: `Monitor priority, inheritable from a linked profile. Use jsonencode({ value = "P1" }).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"query": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: `Monitor queries keyed by query label. Use jsonencode({ A = { mode = "promql", promql = "..." } }).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"search_mode": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: `Logs monitors only. Distinguishes authoring a fresh search ('new') from selecting a saved one ('saved'). Defaults to 'new' when omitted; ignored for non-logs monitor types.`,
			},
			"silence": schema.ListAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: `IDs of silence windows that suppress this monitor's alerts.`,
				ElementType: types.StringType,
			},
			"team": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: `Owning team, inheritable from a linked profile. Use jsonencode({ value = "<team-name>" }).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"template_params": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    false,
				Description: `Template parameter bindings keyed by query label. Use jsonencode({ A = { ... } }).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"type": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: `Monitor type, which determines the detection strategy (for example threshold, change, anomaly, outlier, forecast, or logs).`,
			},
			"unit": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: `Optional unit label applied to the monitor's values.`,
			},
		},
	}
}

func (r *MonitorResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	clients, ok := req.ProviderData.(*ProviderClients)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *ProviderClients, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.client = clients.RC
	r.api = newMonitorAPI(r.client)
}

func (r *MonitorResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var model MonitorModel
	var plan types.Object
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(plan.As(ctx, &model, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)
	if resp.Diagnostics.HasError() {
		return
	}
	apiModel, err := r.api.Create(ctx, model)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		return
	}
	applyMonitorAPIToState(apiModel, &model, true, false)
	resp.Diagnostics.Append(resp.State.Set(ctx, &model)...)
}

func (r *MonitorResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var model MonitorModel
	resp.Diagnostics.Append(req.State.Get(ctx, &model)...)
	if resp.Diagnostics.HasError() {
		return
	}
	apiModel, err := r.api.Read(ctx, model)
	if restclient.IsNotFound(err) {
		resp.State.RemoveResource(ctx)
		return
	}
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		return
	}
	applyMonitorAPIToState(apiModel, &model, true, isMonitorImportState(&model))
	resp.Diagnostics.Append(resp.State.Set(ctx, &model)...)
}

func (r *MonitorResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var model MonitorModel
	var plan types.Object
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(plan.As(ctx, &model, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)
	if resp.Diagnostics.HasError() {
		return
	}
	apiModel, err := r.api.Update(ctx, model)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		return
	}
	applyMonitorAPIToState(apiModel, &model, true, false)
	resp.Diagnostics.Append(resp.State.Set(ctx, &model)...)
}

func (r *MonitorResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var model MonitorModel
	resp.Diagnostics.Append(req.State.Get(ctx, &model)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.api.Delete(ctx, model); err != nil && !restclient.IsNotFound(err) {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
	}
}

func (r *MonitorResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

func isMonitorImportState(state *MonitorModel) bool {
	if state == nil {
		return false
	}
	if state.DatasetID.IsNull() || state.DatasetID.IsUnknown() {
		return true
	}
	if state.Enabled.IsNull() || state.Enabled.IsUnknown() {
		return true
	}
	if state.Expr.IsNull() || state.Expr.IsUnknown() {
		return true
	}
	if state.FiringCondition.IsNull() || state.FiringCondition.IsUnknown() {
		return true
	}
	if state.FiringRule.IsNull() || state.FiringRule.IsUnknown() {
		return true
	}
	if state.Metadata.IsNull() || state.Metadata.IsUnknown() {
		return true
	}
	if state.Name.IsNull() || state.Name.IsUnknown() {
		return true
	}
	if state.Notification.IsNull() || state.Notification.IsUnknown() {
		return true
	}
	if state.Priority.IsNull() || state.Priority.IsUnknown() {
		return true
	}
	if state.Query.IsNull() || state.Query.IsUnknown() {
		return true
	}
	if state.Silence.IsNull() || state.Silence.IsUnknown() {
		return true
	}
	if state.Team.IsNull() || state.Team.IsUnknown() {
		return true
	}
	if state.Type.IsNull() || state.Type.IsUnknown() {
		return true
	}
	return false
}

func applyMonitorAPIToState(api *MonitorModel, state *MonitorModel, preserveInputs bool, fillMissingInputs bool) {
	if api == nil || state == nil {
		return
	}
	if !preserveInputs || (fillMissingInputs && (state.DatasetID.IsNull() || state.DatasetID.IsUnknown())) {
		if !api.DatasetID.IsNull() && !api.DatasetID.IsUnknown() {
			state.DatasetID = api.DatasetID
		}
	}
	if !preserveInputs || (fillMissingInputs && (state.Description.IsNull() || state.Description.IsUnknown())) {
		if !api.Description.IsNull() && !api.Description.IsUnknown() {
			state.Description = api.Description
		}
	}
	if !api.DetectionConfig.IsNull() && !api.DetectionConfig.IsUnknown() {
		state.DetectionConfig = api.DetectionConfig
	}
	if state.DetectionConfig.IsUnknown() {
		state.DetectionConfig = jsontypes.NewNormalizedNull()
	}
	if !preserveInputs || (fillMissingInputs && (state.Enabled.IsNull() || state.Enabled.IsUnknown())) {
		if !api.Enabled.IsNull() && !api.Enabled.IsUnknown() {
			state.Enabled = api.Enabled
		}
	}
	if !preserveInputs || (fillMissingInputs && (state.Expr.IsNull() || state.Expr.IsUnknown())) {
		if !api.Expr.IsNull() && !api.Expr.IsUnknown() {
			state.Expr = api.Expr
		}
	}
	if !preserveInputs || (fillMissingInputs && (state.FiringCondition.IsNull() || state.FiringCondition.IsUnknown())) {
		if !api.FiringCondition.IsNull() && !api.FiringCondition.IsUnknown() {
			state.FiringCondition = api.FiringCondition
		}
	}
	if !preserveInputs || (fillMissingInputs && (state.FiringRule.IsNull() || state.FiringRule.IsUnknown())) {
		if !api.FiringRule.IsNull() && !api.FiringRule.IsUnknown() {
			state.FiringRule = api.FiringRule
		}
	}
	if !preserveInputs || (fillMissingInputs && (state.ID.IsNull() || state.ID.IsUnknown())) {
		if !api.ID.IsNull() && !api.ID.IsUnknown() {
			state.ID = api.ID
		}
	}
	if !api.ManagedBy.IsNull() && !api.ManagedBy.IsUnknown() {
		state.ManagedBy = api.ManagedBy
	} else if state.ManagedBy.IsNull() || state.ManagedBy.IsUnknown() {
		state.ManagedBy = types.StringValue("")
	}
	if !preserveInputs || (fillMissingInputs && (state.Metadata.IsNull() || state.Metadata.IsUnknown())) {
		if !api.Metadata.IsNull() && !api.Metadata.IsUnknown() {
			state.Metadata = api.Metadata
		}
	}
	if !preserveInputs || (fillMissingInputs && (state.Name.IsNull() || state.Name.IsUnknown())) {
		if !api.Name.IsNull() && !api.Name.IsUnknown() {
			state.Name = api.Name
		}
	}
	if !preserveInputs || (fillMissingInputs && (state.Notification.IsNull() || state.Notification.IsUnknown())) {
		if !api.Notification.IsNull() && !api.Notification.IsUnknown() {
			state.Notification = api.Notification
		}
	}
	if !preserveInputs || (fillMissingInputs && (state.Priority.IsNull() || state.Priority.IsUnknown())) {
		if !api.Priority.IsNull() && !api.Priority.IsUnknown() {
			state.Priority = api.Priority
		}
	}
	if !preserveInputs || (fillMissingInputs && (state.Query.IsNull() || state.Query.IsUnknown())) {
		if !api.Query.IsNull() && !api.Query.IsUnknown() {
			state.Query = api.Query
		}
	}
	if !api.SearchMode.IsNull() && !api.SearchMode.IsUnknown() {
		state.SearchMode = api.SearchMode
	}
	if state.SearchMode.IsUnknown() {
		state.SearchMode = types.StringNull()
	}
	if !preserveInputs || (fillMissingInputs && (state.Silence.IsNull() || state.Silence.IsUnknown())) {
		if !api.Silence.IsNull() && !api.Silence.IsUnknown() {
			state.Silence = api.Silence
		}
	}
	if elementType := state.Silence.ElementType(context.Background()); elementType == nil {
		state.Silence = types.ListNull(types.StringType)
	}
	if !preserveInputs || (fillMissingInputs && (state.Team.IsNull() || state.Team.IsUnknown())) {
		if !api.Team.IsNull() && !api.Team.IsUnknown() {
			state.Team = api.Team
		}
	}
	if !preserveInputs || (fillMissingInputs && (state.TemplateParams.IsNull() || state.TemplateParams.IsUnknown())) {
		if !api.TemplateParams.IsNull() && !api.TemplateParams.IsUnknown() {
			state.TemplateParams = api.TemplateParams
		}
	}
	if !preserveInputs || (fillMissingInputs && (state.Type.IsNull() || state.Type.IsUnknown())) {
		if !api.Type.IsNull() && !api.Type.IsUnknown() {
			state.Type = api.Type
		}
	}
	if !api.Unit.IsNull() && !api.Unit.IsUnknown() {
		state.Unit = api.Unit
	}
	if state.Unit.IsUnknown() {
		state.Unit = types.StringNull()
	}
}

func MonitorDebug(value any) string {
	return fmt.Sprintf("%v", value)
}
