// Code generated by tools/codegen. DO NOT EDIT.
package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"unicode"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ = context.Background
var _ = jsontypes.NormalizedType{}

type MonitorModel struct {
	DatasetID       types.String         `tfsdk:"dataset_id" json:"datasetId,omitempty"`
	Description     types.String         `tfsdk:"description" json:"description,omitempty"`
	DetectionConfig jsontypes.Normalized `tfsdk:"detection_config" json:"detectionConfig,omitempty"`
	Enabled         types.Bool           `tfsdk:"enabled" json:"enabled,omitempty"`
	Expr            types.List           `tfsdk:"expr" json:"expr,omitempty"`
	FiringCondition types.Object         `tfsdk:"firing_condition" json:"firingCondition,omitempty"`
	FiringRule      types.Object         `tfsdk:"firing_rule" json:"firingRule,omitempty"`
	ID              types.String         `tfsdk:"id" json:"id,omitempty"`
	ManagedBy       types.String         `tfsdk:"managed_by" json:"managedBy,omitempty"`
	Metadata        types.Map            `tfsdk:"metadata" json:"metadata,omitempty"`
	Name            types.String         `tfsdk:"name" json:"name,omitempty"`
	Notification    jsontypes.Normalized `tfsdk:"notification" json:"notification,omitempty"`
	Priority        types.Object         `tfsdk:"priority" json:"priority,omitempty"`
	Query           types.Map            `tfsdk:"query" json:"query,omitempty"`
	SearchMode      types.String         `tfsdk:"search_mode" json:"searchMode,omitempty"`
	Team            types.Object         `tfsdk:"team" json:"team,omitempty"`
	TemplateParams  jsontypes.Normalized `tfsdk:"template_params" json:"templateParams,omitempty"`
	Type            types.String         `tfsdk:"type" json:"type,omitempty"`
	Unit            types.String         `tfsdk:"unit" json:"unit,omitempty"`
}

type MonitorResourceModel struct {
	DatasetID       types.String         `tfsdk:"dataset_id" json:"datasetId,omitempty"`
	Description     types.String         `tfsdk:"description" json:"description,omitempty"`
	DetectionConfig jsontypes.Normalized `tfsdk:"detection_config" json:"detectionConfig,omitempty"`
	Enabled         types.Bool           `tfsdk:"enabled" json:"enabled,omitempty"`
	Expr            types.List           `tfsdk:"expr" json:"expr,omitempty"`
	FiringCondition types.Object         `tfsdk:"firing_condition" json:"firingCondition,omitempty"`
	FiringRule      types.Object         `tfsdk:"firing_rule" json:"firingRule,omitempty"`
	ID              types.String         `tfsdk:"id" json:"id,omitempty"`
	ManagedBy       types.String         `tfsdk:"managed_by" json:"managedBy,omitempty"`
	Metadata        types.Map            `tfsdk:"metadata" json:"metadata,omitempty"`
	Name            types.String         `tfsdk:"name" json:"name,omitempty"`
	Notification    jsontypes.Normalized `tfsdk:"notification" json:"notification,omitempty"`
	Priority        types.Object         `tfsdk:"priority" json:"priority,omitempty"`
	Query           types.Map            `tfsdk:"query" json:"query,omitempty"`
	SearchMode      types.String         `tfsdk:"search_mode" json:"searchMode,omitempty"`
	Team            types.Object         `tfsdk:"team" json:"team,omitempty"`
	TemplateParams  jsontypes.Normalized `tfsdk:"template_params" json:"templateParams,omitempty"`
	Type            types.String         `tfsdk:"type" json:"type,omitempty"`
	Unit            types.String         `tfsdk:"unit" json:"unit,omitempty"`
}

type MonitorDataSourceModel struct {
	DatasetID       types.String         `tfsdk:"dataset_id" json:"datasetId,omitempty"`
	Description     types.String         `tfsdk:"description" json:"description,omitempty"`
	DetectionConfig jsontypes.Normalized `tfsdk:"detection_config" json:"detectionConfig,omitempty"`
	Enabled         types.Bool           `tfsdk:"enabled" json:"enabled,omitempty"`
	Expr            types.List           `tfsdk:"expr" json:"expr,omitempty"`
	FiringCondition types.Object         `tfsdk:"firing_condition" json:"firingCondition,omitempty"`
	FiringRule      types.Object         `tfsdk:"firing_rule" json:"firingRule,omitempty"`
	ID              types.String         `tfsdk:"id" json:"id,omitempty"`
	ManagedBy       types.String         `tfsdk:"managed_by" json:"managedBy,omitempty"`
	Metadata        types.Map            `tfsdk:"metadata" json:"metadata,omitempty"`
	Name            types.String         `tfsdk:"name" json:"name,omitempty"`
	Notification    jsontypes.Normalized `tfsdk:"notification" json:"notification,omitempty"`
	Priority        types.Object         `tfsdk:"priority" json:"priority,omitempty"`
	Query           types.Map            `tfsdk:"query" json:"query,omitempty"`
	SearchMode      types.String         `tfsdk:"search_mode" json:"searchMode,omitempty"`
	Team            types.Object         `tfsdk:"team" json:"team,omitempty"`
	TemplateParams  jsontypes.Normalized `tfsdk:"template_params" json:"templateParams,omitempty"`
	Type            types.String         `tfsdk:"type" json:"type,omitempty"`
	Unit            types.String         `tfsdk:"unit" json:"unit,omitempty"`
}

type MonitorAPIModel struct {
	DatasetID       *string           `json:"datasetId,omitempty"`
	Description     *string           `json:"description,omitempty"`
	DetectionConfig any               `json:"detectionConfig,omitempty"`
	Enabled         *bool             `json:"enabled,omitempty"`
	Expr            any               `json:"expr,omitempty"`
	FiringCondition any               `json:"firingCondition,omitempty"`
	FiringRule      any               `json:"firingRule,omitempty"`
	ID              *string           `json:"id,omitempty"`
	ManagedBy       *string           `json:"managedBy,omitempty"`
	Metadata        map[string]string `json:"metadata,omitempty"`
	Name            *string           `json:"name,omitempty"`
	Notification    any               `json:"notification,omitempty"`
	Priority        any               `json:"priority,omitempty"`
	Query           any               `json:"query,omitempty"`
	SearchMode      *string           `json:"searchMode,omitempty"`
	Team            any               `json:"team,omitempty"`
	TemplateParams  any               `json:"templateParams,omitempty"`
	Type            *string           `json:"type,omitempty"`
	Unit            *string           `json:"unit,omitempty"`
}

type MonitorExprModel struct {
	DatasetID   types.String  `tfsdk:"dataset_id" json:"datasetId,omitempty"`
	Label       types.String  `tfsdk:"label" json:"label,omitempty"`
	Left        types.String  `tfsdk:"left" json:"left,omitempty"`
	Operation   types.String  `tfsdk:"operation" json:"operation,omitempty"`
	QueryLabels types.List    `tfsdk:"query_labels" json:"queryLabels,omitempty"`
	Right       types.String  `tfsdk:"right" json:"right,omitempty"`
	Scalar      types.Float64 `tfsdk:"scalar" json:"scalar,omitempty"`
	Text        types.String  `tfsdk:"text" json:"text,omitempty"`
}

type MonitorExprAPIModel struct {
	DatasetID   *string  `json:"datasetId,omitempty"`
	Label       *string  `json:"label,omitempty"`
	Left        *string  `json:"left,omitempty"`
	Operation   *string  `json:"operation,omitempty"`
	QueryLabels []string `json:"queryLabels,omitempty"`
	Right       *string  `json:"right,omitempty"`
	Scalar      *float64 `json:"scalar,omitempty"`
	Text        *string  `json:"text,omitempty"`
}

func MonitorExprAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"dataset_id":   types.StringType,
		"label":        types.StringType,
		"left":         types.StringType,
		"operation":    types.StringType,
		"query_labels": types.ListType{ElemType: types.StringType},
		"right":        types.StringType,
		"scalar":       types.Float64Type,
		"text":         types.StringType,
	}
}

type MonitorFiringConditionModel struct {
	ClearDelay types.Float64 `tfsdk:"clear_delay" json:"clear_delay,omitempty"`
	FireDelay  types.Float64 `tfsdk:"fire_delay" json:"fire_delay,omitempty"`
}

type MonitorFiringConditionAPIModel struct {
	ClearDelay *float64 `json:"clear_delay,omitempty"`
	FireDelay  *float64 `json:"fire_delay,omitempty"`
}

func MonitorFiringConditionAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"clear_delay": types.Float64Type,
		"fire_delay":  types.Float64Type,
	}
}

type MonitorFiringRuleModel struct {
	Label       types.String `tfsdk:"label" json:"label,omitempty"`
	Overrides   types.List   `tfsdk:"overrides" json:"overrides,omitempty"`
	ShowOnChart types.Bool   `tfsdk:"show_on_chart" json:"showOnChart,omitempty"`
	Threshold   types.List   `tfsdk:"threshold" json:"threshold,omitempty"`
}

type MonitorFiringRuleAPIModel struct {
	Label       *string `json:"label,omitempty"`
	Overrides   any     `json:"overrides,omitempty"`
	ShowOnChart *bool   `json:"showOnChart,omitempty"`
	Threshold   any     `json:"threshold,omitempty"`
}

func MonitorFiringRuleAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"label":         types.StringType,
		"overrides":     types.ListType{ElemType: types.ObjectType{AttrTypes: MonitorFiringRuleOverridesAttrTypes()}},
		"show_on_chart": types.BoolType,
		"threshold":     types.ListType{ElemType: types.ObjectType{AttrTypes: MonitorFiringRuleThresholdAttrTypes()}},
	}
}

type MonitorFiringRuleOverridesModel struct {
	Enabled      types.Bool   `tfsdk:"enabled" json:"enabled,omitempty"`
	ExcludedTags types.List   `tfsdk:"excluded_tags" json:"excludedTags,omitempty"`
	IncludedTags types.List   `tfsdk:"included_tags" json:"includedTags,omitempty"`
	Name         types.String `tfsdk:"name" json:"name,omitempty"`
	ShowOnChart  types.Bool   `tfsdk:"show_on_chart" json:"showOnChart,omitempty"`
	Threshold    types.List   `tfsdk:"threshold" json:"threshold,omitempty"`
}

type MonitorFiringRuleOverridesAPIModel struct {
	Enabled      *bool    `json:"enabled,omitempty"`
	ExcludedTags []string `json:"excludedTags,omitempty"`
	IncludedTags []string `json:"includedTags,omitempty"`
	Name         *string  `json:"name,omitempty"`
	ShowOnChart  *bool    `json:"showOnChart,omitempty"`
	Threshold    any      `json:"threshold,omitempty"`
}

func MonitorFiringRuleOverridesAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"enabled":       types.BoolType,
		"excluded_tags": types.ListType{ElemType: types.StringType},
		"included_tags": types.ListType{ElemType: types.StringType},
		"name":          types.StringType,
		"show_on_chart": types.BoolType,
		"threshold":     types.ListType{ElemType: types.ObjectType{AttrTypes: MonitorFiringRuleOverridesThresholdAttrTypes()}},
	}
}

type MonitorFiringRuleOverridesThresholdModel struct {
	ExcludedTags   types.List    `tfsdk:"excluded_tags" json:"excludedTags,omitempty"`
	IncludedTags   types.List    `tfsdk:"included_tags" json:"includedTags,omitempty"`
	Limit          types.Float64 `tfsdk:"limit" json:"limit,omitempty"`
	Operator       types.String  `tfsdk:"operator" json:"operator,omitempty"`
	Severity       types.String  `tfsdk:"severity" json:"severity,omitempty"`
	StdDeviations  types.Float64 `tfsdk:"std_deviations" json:"stdDeviations,omitempty"`
	TimesTriggered types.Float64 `tfsdk:"times_triggered" json:"timesTriggered,omitempty"`
}

type MonitorFiringRuleOverridesThresholdAPIModel struct {
	ExcludedTags   []string `json:"excludedTags,omitempty"`
	IncludedTags   []string `json:"includedTags,omitempty"`
	Limit          *float64 `json:"limit,omitempty"`
	Operator       *string  `json:"operator,omitempty"`
	Severity       *string  `json:"severity,omitempty"`
	StdDeviations  *float64 `json:"stdDeviations,omitempty"`
	TimesTriggered *float64 `json:"timesTriggered,omitempty"`
}

func MonitorFiringRuleOverridesThresholdAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"excluded_tags":   types.ListType{ElemType: types.StringType},
		"included_tags":   types.ListType{ElemType: types.StringType},
		"limit":           types.Float64Type,
		"operator":        types.StringType,
		"severity":        types.StringType,
		"std_deviations":  types.Float64Type,
		"times_triggered": types.Float64Type,
	}
}

type MonitorFiringRuleThresholdModel struct {
	ExcludedTags   types.List    `tfsdk:"excluded_tags" json:"excludedTags,omitempty"`
	IncludedTags   types.List    `tfsdk:"included_tags" json:"includedTags,omitempty"`
	Limit          types.Float64 `tfsdk:"limit" json:"limit,omitempty"`
	Operator       types.String  `tfsdk:"operator" json:"operator,omitempty"`
	Severity       types.String  `tfsdk:"severity" json:"severity,omitempty"`
	StdDeviations  types.Float64 `tfsdk:"std_deviations" json:"stdDeviations,omitempty"`
	TimesTriggered types.Float64 `tfsdk:"times_triggered" json:"timesTriggered,omitempty"`
}

type MonitorFiringRuleThresholdAPIModel struct {
	ExcludedTags   []string `json:"excludedTags,omitempty"`
	IncludedTags   []string `json:"includedTags,omitempty"`
	Limit          *float64 `json:"limit,omitempty"`
	Operator       *string  `json:"operator,omitempty"`
	Severity       *string  `json:"severity,omitempty"`
	StdDeviations  *float64 `json:"stdDeviations,omitempty"`
	TimesTriggered *float64 `json:"timesTriggered,omitempty"`
}

func MonitorFiringRuleThresholdAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"excluded_tags":   types.ListType{ElemType: types.StringType},
		"included_tags":   types.ListType{ElemType: types.StringType},
		"limit":           types.Float64Type,
		"operator":        types.StringType,
		"severity":        types.StringType,
		"std_deviations":  types.Float64Type,
		"times_triggered": types.Float64Type,
	}
}

type MonitorPriorityModel struct {
	Value types.String `tfsdk:"value" json:"value,omitempty"`
}

type MonitorPriorityAPIModel struct {
	Value *string `json:"value,omitempty"`
}

func MonitorPriorityAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"value": types.StringType,
	}
}

type MonitorQueryModel struct {
	Builder     types.Object `tfsdk:"builder" json:"builder,omitempty"`
	DatasetID   types.String `tfsdk:"dataset_id" json:"datasetId,omitempty"`
	DisplayName types.String `tfsdk:"display_name" json:"displayName,omitempty"`
	LogsBuilder types.Object `tfsdk:"logs_builder" json:"logsBuilder,omitempty"`
	Mode        types.String `tfsdk:"mode" json:"mode,omitempty"`
	Params      types.Map    `tfsdk:"params" json:"params,omitempty"`
	Promql      types.String `tfsdk:"promql" json:"promql,omitempty"`
}

type MonitorQueryAPIModel struct {
	Builder     any               `json:"builder,omitempty"`
	DatasetID   *string           `json:"datasetId,omitempty"`
	DisplayName *string           `json:"displayName,omitempty"`
	LogsBuilder any               `json:"logsBuilder,omitempty"`
	Mode        *string           `json:"mode,omitempty"`
	Params      map[string]string `json:"params,omitempty"`
	Promql      *string           `json:"promql,omitempty"`
}

func MonitorQueryAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"builder":      types.ObjectType{AttrTypes: MonitorQueryBuilderAttrTypes()},
		"dataset_id":   types.StringType,
		"display_name": types.StringType,
		"logs_builder": types.ObjectType{AttrTypes: MonitorQueryLogsBuilderAttrTypes()},
		"mode":         types.StringType,
		"params":       types.MapType{ElemType: types.StringType},
		"promql":       types.StringType,
	}
}

type MonitorQueryBuilderModel struct {
	Aggregation      types.String `tfsdk:"aggregation" json:"aggregation,omitempty"`
	EvaluationWindow types.Object `tfsdk:"evaluation_window" json:"evaluationWindow,omitempty"`
	GroupBy          types.List   `tfsdk:"group_by" json:"groupBy,omitempty"`
	LabelFilters     types.List   `tfsdk:"label_filters" json:"labelFilters,omitempty"`
	Metric           types.String `tfsdk:"metric" json:"metric,omitempty"`
	Units            types.String `tfsdk:"units" json:"units,omitempty"`
}

type MonitorQueryBuilderAPIModel struct {
	Aggregation      *string  `json:"aggregation,omitempty"`
	EvaluationWindow any      `json:"evaluationWindow,omitempty"`
	GroupBy          []string `json:"groupBy,omitempty"`
	LabelFilters     any      `json:"labelFilters,omitempty"`
	Metric           *string  `json:"metric,omitempty"`
	Units            *string  `json:"units,omitempty"`
}

func MonitorQueryBuilderAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"aggregation":       types.StringType,
		"evaluation_window": types.ObjectType{AttrTypes: MonitorQueryBuilderEvaluationWindowAttrTypes()},
		"group_by":          types.ListType{ElemType: types.StringType},
		"label_filters":     types.ListType{ElemType: types.ObjectType{AttrTypes: MonitorQueryBuilderLabelFiltersAttrTypes()}},
		"metric":            types.StringType,
		"units":             types.StringType,
	}
}

type MonitorQueryBuilderEvaluationWindowModel struct {
	Unit  types.String  `tfsdk:"unit" json:"unit,omitempty"`
	Value types.Float64 `tfsdk:"value" json:"value,omitempty"`
}

type MonitorQueryBuilderEvaluationWindowAPIModel struct {
	Unit  *string  `json:"unit,omitempty"`
	Value *float64 `json:"value,omitempty"`
}

func MonitorQueryBuilderEvaluationWindowAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"unit":  types.StringType,
		"value": types.Float64Type,
	}
}

type MonitorQueryBuilderLabelFiltersModel struct {
	Key   types.String `tfsdk:"key" json:"key,omitempty"`
	Op    types.String `tfsdk:"op" json:"op,omitempty"`
	Value types.String `tfsdk:"value" json:"value,omitempty"`
}

type MonitorQueryBuilderLabelFiltersAPIModel struct {
	Key   *string `json:"key,omitempty"`
	Op    *string `json:"op,omitempty"`
	Value *string `json:"value,omitempty"`
}

func MonitorQueryBuilderLabelFiltersAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"key":   types.StringType,
		"op":    types.StringType,
		"value": types.StringType,
	}
}

type MonitorQueryLogsBuilderModel struct {
	Dataset          types.String `tfsdk:"dataset" json:"dataset,omitempty"`
	EvaluationWindow types.Object `tfsdk:"evaluation_window" json:"evaluationWindow,omitempty"`
	Field            types.String `tfsdk:"field" json:"field,omitempty"`
	GroupBy          types.List   `tfsdk:"group_by" json:"groupBy,omitempty"`
	Operator         types.String `tfsdk:"operator" json:"operator,omitempty"`
	ParentSearch     types.String `tfsdk:"parent_search" json:"parentSearch,omitempty"`
	SavedSearchID    types.String `tfsdk:"saved_search_id" json:"savedSearchId,omitempty"`
}

type MonitorQueryLogsBuilderAPIModel struct {
	Dataset          *string  `json:"dataset,omitempty"`
	EvaluationWindow any      `json:"evaluationWindow,omitempty"`
	Field            *string  `json:"field,omitempty"`
	GroupBy          []string `json:"groupBy,omitempty"`
	Operator         *string  `json:"operator,omitempty"`
	ParentSearch     *string  `json:"parentSearch,omitempty"`
	SavedSearchID    *string  `json:"savedSearchId,omitempty"`
}

func MonitorQueryLogsBuilderAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"dataset":           types.StringType,
		"evaluation_window": types.ObjectType{AttrTypes: MonitorQueryLogsBuilderEvaluationWindowAttrTypes()},
		"field":             types.StringType,
		"group_by":          types.ListType{ElemType: types.StringType},
		"operator":          types.StringType,
		"parent_search":     types.StringType,
		"saved_search_id":   types.StringType,
	}
}

type MonitorQueryLogsBuilderEvaluationWindowModel struct {
	Unit  types.String  `tfsdk:"unit" json:"unit,omitempty"`
	Value types.Float64 `tfsdk:"value" json:"value,omitempty"`
}

type MonitorQueryLogsBuilderEvaluationWindowAPIModel struct {
	Unit  *string  `json:"unit,omitempty"`
	Value *float64 `json:"value,omitempty"`
}

func MonitorQueryLogsBuilderEvaluationWindowAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"unit":  types.StringType,
		"value": types.Float64Type,
	}
}

type MonitorTeamModel struct {
	Value types.String `tfsdk:"value" json:"value,omitempty"`
}

type MonitorTeamAPIModel struct {
	Value *string `json:"value,omitempty"`
}

func MonitorTeamAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"value": types.StringType,
	}
}

func MonitorTerraformValueToJSON(value attr.Value) (any, error) {
	if value.IsNull() || value.IsUnknown() {
		return nil, nil
	}
	switch typed := value.(type) {
	case types.Bool:
		return typed.ValueBool(), nil
	case types.Int64:
		return typed.ValueInt64(), nil
	case types.Float64:
		return typed.ValueFloat64(), nil
	case jsontypes.Normalized:
		raw := typed.ValueString()
		if raw == "" {
			return map[string]any{}, nil
		}
		var output any
		if err := json.Unmarshal([]byte(raw), &output); err != nil {
			return nil, err
		}
		return output, nil
	case types.String:
		return typed.ValueString(), nil
	case types.List:
		output := make([]any, 0, len(typed.Elements()))
		for _, element := range typed.Elements() {
			value, err := MonitorTerraformValueToJSON(element)
			if err != nil {
				return nil, err
			}
			output = append(output, value)
		}
		return output, nil
	case types.Map:
		output := make(map[string]any, len(typed.Elements()))
		for key, element := range typed.Elements() {
			value, err := MonitorTerraformValueToJSON(element)
			if err != nil {
				return nil, err
			}
			if value == nil {
				continue
			}
			output[key] = value
		}
		return output, nil
	case types.Object:
		output := make(map[string]any, len(typed.Attributes()))
		attributeTypes := typed.AttributeTypes(context.Background())
		attributes := typed.Attributes()
		for key, attribute := range attributes {
			var value any
			var err error
			if attributeType, ok := attributeTypes[key]; ok && attributeType.Equal(jsontypes.NormalizedType{}) {
				value, err = MonitorObjectJSONFromTerraformValue(attribute)
			} else {
				value, err = MonitorTerraformValueToJSON(attribute)
			}
			if err != nil {
				return nil, err
			}
			if value == nil {
				continue
			}
			apiKey := MonitorTerraformNameToAPIName(key)
			output[apiKey] = value
		}
		return output, nil
	case interface{ ValueString() string }:
		return typed.ValueString(), nil
	default:
		return nil, fmt.Errorf("unsupported Terraform value %T", value)
	}
}
func MonitorObjectJSONFromTerraformValue(value attr.Value) (any, error) {
	if value.IsNull() || value.IsUnknown() {
		return nil, nil
	}
	typed, ok := value.(interface{ ValueString() string })
	if !ok {
		return nil, fmt.Errorf("expected normalized JSON string, got %T", value)
	}
	raw := typed.ValueString()
	if raw == "" {
		return map[string]any{}, nil
	}
	var output any
	if err := json.Unmarshal([]byte(raw), &output); err != nil {
		return nil, err
	}
	return output, nil
}

func MonitorTerraformNameToAPIName(name string) string {
	prefix := ""
	if strings.HasPrefix(name, "__template_") {
		prefix = "__template_"
		name = strings.TrimPrefix(name, prefix)
	}
	switch name {
	case "clear_delay":
		return prefix + "clear_delay"
	case "fire_delay":
		return prefix + "fire_delay"
	}
	var output strings.Builder
	upperNext := false
	for _, char := range name {
		if char == '_' {
			upperNext = true
			continue
		}
		if upperNext {
			output.WriteRune(unicode.ToUpper(char))
			upperNext = false
			continue
		}
		output.WriteRune(char)
	}
	return prefix + output.String()
}

func MonitorAPIValueToTerraformValue(value any, typ attr.Type) (attr.Value, error) {
	if value == nil {
		return MonitorTerraformNullValue(typ)
	}
	if typ.Equal(types.BoolType) {
		typed, ok := value.(bool)
		if !ok {
			return nil, fmt.Errorf("expected bool, got %T", value)
		}
		return types.BoolValue(typed), nil
	}
	if typ.Equal(types.Int64Type) {
		typed, ok := value.(float64)
		if !ok {
			return nil, fmt.Errorf("expected number, got %T", value)
		}
		return types.Int64Value(int64(typed)), nil
	}
	if typ.Equal(types.Float64Type) {
		typed, ok := value.(float64)
		if !ok {
			return nil, fmt.Errorf("expected number, got %T", value)
		}
		return types.Float64Value(typed), nil
	}
	if typ.Equal(types.StringType) {
		typed, ok := value.(string)
		if !ok {
			return nil, fmt.Errorf("expected string, got %T", value)
		}
		return types.StringValue(typed), nil
	}
	if typ.Equal(jsontypes.NormalizedType{}) {
		if typed, ok := value.(string); ok {
			return jsontypes.NewNormalizedValue(typed), nil
		}
		raw, err := json.Marshal(value)
		if err != nil {
			return nil, err
		}
		return jsontypes.NewNormalizedValue(string(raw)), nil
	}
	switch typed := typ.(type) {
	case types.ListType:
		input, ok := value.([]any)
		if !ok {
			return nil, fmt.Errorf("expected list, got %T", value)
		}
		output := make([]attr.Value, 0, len(input))
		for _, item := range input {
			nested, err := MonitorAPIValueToTerraformValue(item, typed.ElemType)
			if err != nil {
				return nil, err
			}
			output = append(output, nested)
		}
		value, diags := types.ListValue(typed.ElemType, output)
		if diags.HasError() {
			return nil, fmt.Errorf("%v", diags)
		}
		return value, nil
	case types.MapType:
		input, ok := value.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("expected map, got %T", value)
		}
		output := make(map[string]attr.Value, len(input))
		for key, item := range input {
			nested, err := MonitorAPIValueToTerraformValue(item, typed.ElemType)
			if err != nil {
				return nil, err
			}
			output[key] = nested
		}
		value, diags := types.MapValue(typed.ElemType, output)
		if diags.HasError() {
			return nil, fmt.Errorf("%v", diags)
		}
		return value, nil
	case types.ObjectType:
		input, ok := value.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("expected object, got %T", value)
		}
		output := make(map[string]attr.Value, len(typed.AttrTypes))
		for key, attrType := range typed.AttrTypes {
			apiKey := MonitorTerraformNameToAPIName(key)
			item, ok := input[apiKey]
			if !ok {
				item, ok = input[key]
			}
			if !ok {
				nested, err := MonitorTerraformNullValue(attrType)
				if err != nil {
					return nil, err
				}
				output[key] = nested
				continue
			}
			nested, err := MonitorAPIValueToTerraformValue(item, attrType)
			if err != nil {
				return nil, err
			}
			output[key] = nested
		}
		value, diags := types.ObjectValue(typed.AttrTypes, output)
		if diags.HasError() {
			return nil, fmt.Errorf("%v", diags)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("unsupported Terraform type %T", typ)
	}
}

func MonitorTerraformNullValue(typ attr.Type) (attr.Value, error) {
	if typ.Equal(types.BoolType) {
		return types.BoolNull(), nil
	}
	if typ.Equal(types.Int64Type) {
		return types.Int64Null(), nil
	}
	if typ.Equal(types.Float64Type) {
		return types.Float64Null(), nil
	}
	if typ.Equal(types.StringType) {
		return types.StringNull(), nil
	}
	if typ.Equal(jsontypes.NormalizedType{}) {
		return jsontypes.NewNormalizedNull(), nil
	}
	switch typed := typ.(type) {
	case types.ListType:
		return types.ListNull(typed.ElemType), nil
	case types.MapType:
		return types.MapNull(typed.ElemType), nil
	case types.ObjectType:
		return types.ObjectNull(typed.AttrTypes), nil
	default:
		return nil, fmt.Errorf("unsupported Terraform type %T", typ)
	}
}

func (m MonitorModel) MarshalJSON() ([]byte, error) {
	output := map[string]any{}
	if !m.DatasetID.IsNull() && !m.DatasetID.IsUnknown() {
		value, err := MonitorTerraformValueToJSON(m.DatasetID)
		if err != nil {
			return nil, fmt.Errorf("convert dataset_id to API value: %v", err)
		}
		output["datasetId"] = value
	}
	if !m.Description.IsNull() && !m.Description.IsUnknown() {
		value, err := MonitorTerraformValueToJSON(m.Description)
		if err != nil {
			return nil, fmt.Errorf("convert description to API value: %v", err)
		}
		output["description"] = value
	}
	if !m.DetectionConfig.IsNull() && !m.DetectionConfig.IsUnknown() {
		value, err := MonitorObjectJSONFromTerraformValue(m.DetectionConfig)
		if err != nil {
			return nil, fmt.Errorf("convert detection_config to API value: %v", err)
		}
		output["detectionConfig"] = value
	}
	if !m.Enabled.IsNull() && !m.Enabled.IsUnknown() {
		value, err := MonitorTerraformValueToJSON(m.Enabled)
		if err != nil {
			return nil, fmt.Errorf("convert enabled to API value: %v", err)
		}
		output["enabled"] = value
	}
	if !m.Expr.IsNull() && !m.Expr.IsUnknown() {
		value, err := MonitorTerraformValueToJSON(m.Expr)
		if err != nil {
			return nil, fmt.Errorf("convert expr to API value: %v", err)
		}
		output["expr"] = value
	}
	if !m.FiringCondition.IsNull() && !m.FiringCondition.IsUnknown() {
		value, err := MonitorTerraformValueToJSON(m.FiringCondition)
		if err != nil {
			return nil, fmt.Errorf("convert firing_condition to API value: %v", err)
		}
		output["firingCondition"] = value
	}
	if !m.FiringRule.IsNull() && !m.FiringRule.IsUnknown() {
		value, err := MonitorTerraformValueToJSON(m.FiringRule)
		if err != nil {
			return nil, fmt.Errorf("convert firing_rule to API value: %v", err)
		}
		output["firingRule"] = value
	}
	if !m.ID.IsNull() && !m.ID.IsUnknown() {
		value, err := MonitorTerraformValueToJSON(m.ID)
		if err != nil {
			return nil, fmt.Errorf("convert id to API value: %v", err)
		}
		output["id"] = value
	}
	if !m.Metadata.IsNull() && !m.Metadata.IsUnknown() {
		value, err := MonitorTerraformValueToJSON(m.Metadata)
		if err != nil {
			return nil, fmt.Errorf("convert metadata to API value: %v", err)
		}
		output["metadata"] = value
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		value, err := MonitorTerraformValueToJSON(m.Name)
		if err != nil {
			return nil, fmt.Errorf("convert name to API value: %v", err)
		}
		output["name"] = value
	}
	if !m.Notification.IsNull() && !m.Notification.IsUnknown() {
		value, err := MonitorObjectJSONFromTerraformValue(m.Notification)
		if err != nil {
			return nil, fmt.Errorf("convert notification to API value: %v", err)
		}
		output["notification"] = value
	}
	if !m.Priority.IsNull() && !m.Priority.IsUnknown() {
		value, err := MonitorTerraformValueToJSON(m.Priority)
		if err != nil {
			return nil, fmt.Errorf("convert priority to API value: %v", err)
		}
		output["priority"] = value
	}
	if !m.Query.IsNull() && !m.Query.IsUnknown() {
		value, err := MonitorTerraformValueToJSON(m.Query)
		if err != nil {
			return nil, fmt.Errorf("convert query to API value: %v", err)
		}
		output["query"] = value
	}
	if !m.SearchMode.IsNull() && !m.SearchMode.IsUnknown() {
		value, err := MonitorTerraformValueToJSON(m.SearchMode)
		if err != nil {
			return nil, fmt.Errorf("convert search_mode to API value: %v", err)
		}
		output["searchMode"] = value
	}
	if !m.Team.IsNull() && !m.Team.IsUnknown() {
		value, err := MonitorTerraformValueToJSON(m.Team)
		if err != nil {
			return nil, fmt.Errorf("convert team to API value: %v", err)
		}
		output["team"] = value
	}
	if !m.TemplateParams.IsNull() && !m.TemplateParams.IsUnknown() {
		value, err := MonitorObjectJSONFromTerraformValue(m.TemplateParams)
		if err != nil {
			return nil, fmt.Errorf("convert template_params to API value: %v", err)
		}
		output["templateParams"] = value
	}
	if !m.Type.IsNull() && !m.Type.IsUnknown() {
		value, err := MonitorTerraformValueToJSON(m.Type)
		if err != nil {
			return nil, fmt.Errorf("convert type to API value: %v", err)
		}
		output["type"] = value
	}
	if !m.Unit.IsNull() && !m.Unit.IsUnknown() {
		value, err := MonitorTerraformValueToJSON(m.Unit)
		if err != nil {
			return nil, fmt.Errorf("convert unit to API value: %v", err)
		}
		output["unit"] = value
	}
	return json.Marshal(output)
}

func (m *MonitorModel) UnmarshalJSON(data []byte) error {
	var input MonitorAPIModel
	if err := json.Unmarshal(data, &input); err != nil {
		return err
	}
	if input.DatasetID != nil {
		m.DatasetID = types.StringValue(*input.DatasetID)
	} else {
		m.DatasetID = types.StringNull()
	}
	if input.Description != nil {
		m.Description = types.StringValue(*input.Description)
	} else {
		m.Description = types.StringNull()
	}
	if input.DetectionConfig != nil {
		raw, err := json.Marshal(input.DetectionConfig)
		if err != nil {
			return fmt.Errorf("convert detectionConfig from API value: %v", err)
		}
		m.DetectionConfig = jsontypes.NewNormalizedValue(string(raw))
	} else {
		m.DetectionConfig = jsontypes.NewNormalizedNull()
	}
	if input.Enabled != nil {
		m.Enabled = types.BoolValue(*input.Enabled)
	} else {
		m.Enabled = types.BoolNull()
	}
	if input.Expr != nil {
		value, err := MonitorAPIValueToTerraformValue(input.Expr, types.ListType{ElemType: types.ObjectType{AttrTypes: MonitorExprAttrTypes()}})
		if err != nil {
			return fmt.Errorf("convert expr from API value: %v", err)
		}
		m.Expr = value.(types.List)
	} else {
		m.Expr = types.ListNull(types.ObjectType{AttrTypes: MonitorExprAttrTypes()})
	}
	if input.FiringCondition != nil {
		value, err := MonitorAPIValueToTerraformValue(input.FiringCondition, types.ObjectType{AttrTypes: MonitorFiringConditionAttrTypes()})
		if err != nil {
			return fmt.Errorf("convert firingCondition from API value: %v", err)
		}
		m.FiringCondition = value.(types.Object)
	} else {
		m.FiringCondition = types.ObjectNull(MonitorFiringConditionAttrTypes())
	}
	if input.FiringRule != nil {
		value, err := MonitorAPIValueToTerraformValue(input.FiringRule, types.ObjectType{AttrTypes: MonitorFiringRuleAttrTypes()})
		if err != nil {
			return fmt.Errorf("convert firingRule from API value: %v", err)
		}
		m.FiringRule = value.(types.Object)
	} else {
		m.FiringRule = types.ObjectNull(MonitorFiringRuleAttrTypes())
	}
	if input.ID != nil {
		m.ID = types.StringValue(*input.ID)
	} else {
		m.ID = types.StringNull()
	}
	if input.ManagedBy != nil {
		m.ManagedBy = types.StringValue(*input.ManagedBy)
	} else {
		m.ManagedBy = types.StringNull()
	}
	if input.Metadata != nil {
		value, diags := types.MapValueFrom(context.Background(), types.StringType, input.Metadata)
		if diags.HasError() {
			return fmt.Errorf("convert metadata from API value: %v", diags)
		}
		m.Metadata = value
	} else {
		m.Metadata = types.MapNull(types.StringType)
	}
	if input.Name != nil {
		m.Name = types.StringValue(*input.Name)
	} else {
		m.Name = types.StringNull()
	}
	if input.Notification != nil {
		raw, err := json.Marshal(input.Notification)
		if err != nil {
			return fmt.Errorf("convert notification from API value: %v", err)
		}
		m.Notification = jsontypes.NewNormalizedValue(string(raw))
	} else {
		m.Notification = jsontypes.NewNormalizedNull()
	}
	if input.Priority != nil {
		value, err := MonitorAPIValueToTerraformValue(input.Priority, types.ObjectType{AttrTypes: MonitorPriorityAttrTypes()})
		if err != nil {
			return fmt.Errorf("convert priority from API value: %v", err)
		}
		m.Priority = value.(types.Object)
	} else {
		m.Priority = types.ObjectNull(MonitorPriorityAttrTypes())
	}
	if input.Query != nil {
		value, err := MonitorAPIValueToTerraformValue(input.Query, types.MapType{ElemType: types.ObjectType{AttrTypes: MonitorQueryAttrTypes()}})
		if err != nil {
			return fmt.Errorf("convert query from API value: %v", err)
		}
		m.Query = value.(types.Map)
	} else {
		m.Query = types.MapNull(types.ObjectType{AttrTypes: MonitorQueryAttrTypes()})
	}
	if input.SearchMode != nil {
		m.SearchMode = types.StringValue(*input.SearchMode)
	} else {
		m.SearchMode = types.StringNull()
	}
	if input.Team != nil {
		value, err := MonitorAPIValueToTerraformValue(input.Team, types.ObjectType{AttrTypes: MonitorTeamAttrTypes()})
		if err != nil {
			return fmt.Errorf("convert team from API value: %v", err)
		}
		m.Team = value.(types.Object)
	} else {
		m.Team = types.ObjectNull(MonitorTeamAttrTypes())
	}
	if input.TemplateParams != nil {
		raw, err := json.Marshal(input.TemplateParams)
		if err != nil {
			return fmt.Errorf("convert templateParams from API value: %v", err)
		}
		m.TemplateParams = jsontypes.NewNormalizedValue(string(raw))
	} else {
		m.TemplateParams = jsontypes.NewNormalizedNull()
	}
	if input.Type != nil {
		m.Type = types.StringValue(*input.Type)
	} else {
		m.Type = types.StringNull()
	}
	if input.Unit != nil {
		m.Unit = types.StringValue(*input.Unit)
	} else {
		m.Unit = types.StringNull()
	}
	return nil
}
