// Code generated by tools/codegen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/criblio/terraform-provider-criblio/internal/restclient"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ = jsontypes.NormalizedType{}
var _ = types.String{}

var _ datasource.DataSource = &MonitorDataSource{}
var _ datasource.DataSourceWithConfigure = &MonitorDataSource{}

type MonitorDataSource struct {
	client *restclient.Client
	api    MonitorAPI
}

func NewMonitorDataSource() datasource.DataSource {
	return &MonitorDataSource{}
}

func (d *MonitorDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_monitor"
}

func (d *MonitorDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Monitor Data Source",
		Attributes: map[string]schema.Attribute{
			"dataset_id": schema.StringAttribute{
				Computed: true,
			},
			"description": schema.StringAttribute{
				Computed: true,
			},
			"detection_config": schema.StringAttribute{
				Computed:    true,
				Description: `Detection configuration as JSON.`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"enabled": schema.BoolAttribute{
				Computed: true,
			},
			"expr": schema.StringAttribute{
				Computed:    true,
				Description: `Expression transformations as JSON. Use jsonencode([...]).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"firing_condition": schema.StringAttribute{
				Computed:    true,
				Description: `Firing condition as JSON. Use jsonencode({ fire_delay = N, clear_delay = M }).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"firing_rule": schema.StringAttribute{
				Computed:    true,
				Description: `Firing rule as JSON.`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"id": schema.StringAttribute{
				Required: true,
			},
			"managed_by": schema.StringAttribute{
				Computed:    true,
				Description: `Stamped 'terraform' by the backend when provisioned via the Terraform provider (cribl/cribl#43133).`,
			},
			"metadata": schema.StringAttribute{
				Computed:    true,
				Description: `Metadata as JSON. Use jsonencode({}).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"name": schema.StringAttribute{
				Computed: true,
			},
			"notification": schema.StringAttribute{
				Computed:    true,
				Description: `Notification config as JSON.`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"priority": schema.StringAttribute{
				Computed:    true,
				Description: `Priority config as JSON. Use jsonencode({ value = "P1" }).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"query": schema.StringAttribute{
				Computed:    true,
				Description: `Query config as JSON. Use jsonencode({ A = { mode = "promql", promql = "..." } }).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"silence": schema.ListAttribute{
				Computed:    true,
				Description: `List of silence rules.`,
				ElementType: jsontypes.NormalizedType{},
			},
			"team": schema.StringAttribute{
				Computed:    true,
				Description: `Team config as JSON. Use jsonencode({ value = "<team-name>" }).`,
				CustomType:  jsontypes.NormalizedType{},
			},
			"type": schema.StringAttribute{
				Computed: true,
			},
			"unit": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

func (d *MonitorDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	clients, ok := req.ProviderData.(*ProviderClients)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *ProviderClients, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	d.client = clients.RC
	d.api = newMonitorAPI(d.client)
}

func (d *MonitorDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var model MonitorModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &model)...)
	if resp.Diagnostics.HasError() {
		return
	}
	apiModel, err := d.api.Read(ctx, model)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		return
	}
	applyMonitorAPIToState(apiModel, &model, false, false)
	resp.Diagnostics.Append(resp.State.Set(ctx, &model)...)
}

func MonitorDataSourceDebug(value any) string {
	return fmt.Sprintf("%v", value)
}
